#!/usr/bin/python3
print("The Zen of Python, by Tim Peters\n \nBeautiful is better than ugly.\n")
print("Explicit is better than implicit.\nSimple is better than complex.\n")
print("Complex is better than complicated.\nFlat is better than nested.\n")
print("Sparse is better than dense.\nReadability counts.\n")
print("Special cases aren't special enough to break the rules.\n")
print("Although practicality beats purity.\nErrors should never pass silently.\n")
print("Unless explicitly silenced.\n")
print("In the face of ambiguity, refuse the temptation to guess.\n")
print("There should be one-- and preferably only one --obvious way to do it.\n")
print("Although that way may not be obvious at first unless you're Dutch.\n")
print("Now is better than never.\nAlthough never is often better than *right* now.\n")
print("If the implementation is hard to explain, it's a bad idea.\n")
print("If the implementation is easy to explain, it may be a good idea.\n")
print("Namespaces are one honking great idea -- let's do more of those!")
